# Generated by Django 5.1.6 on 2025-03-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_votacao_pauta_alter_votacao_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pautas_pdfs/'),
        ),
    ]
