# Generated by Django 5.1.6 on 2025-03-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pauta_arquivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='status',
            field=models.CharField(choices=[('Em Espera', 'Em Espera'), ('Em Votação', 'Em Votação'), ('Encerrada', 'Encerrada')], default='Em Espera', max_length=20),
        ),
    ]
