# Generated by Django 5.1.6 on 2025-03-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pauta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauta',
            name='status',
            field=models.CharField(choices=[('Em Espera', 'Em Espera'), ('Em Votação', 'Em Votação'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada'), ('Encerrada', 'Encerrada')], default='Em Espera', max_length=20),
        ),
    ]
