# Generated by Django 5.1.6 on 2025-03-15 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pauta_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessao')),
                ('vereador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vereador')),
            ],
        ),
    ]
