# Generated by Django 5.1.6 on 2025-03-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_presencaregistrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='encerrada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
