# Generated by Django 5.1.6 on 2025-03-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sessao_encerrada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='votacao_aberta',
            field=models.BooleanField(default=True),
        ),
    ]
