# Generated by Django 5.1.6 on 2025-03-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pauta_votacao_aberta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pauta',
            name='votacao_aberta',
        ),
        migrations.AddField(
            model_name='pauta',
            name='tipo_votacao',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada')], default='Aberta', max_length=10),
        ),
    ]
