# Generated by Django 5.1.6 on 2025-03-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_pauta_votacao_aberta_pauta_tipo_votacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pauta',
            name='tipo_votacao',
        ),
        migrations.AddField(
            model_name='pauta',
            name='votacao_aberta',
            field=models.BooleanField(default=True),
        ),
    ]
