# Generated by Django 5.1.6 on 2025-03-18 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pauta_tipo_votacao_votacao_data_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacao',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
