# Generated by Django 5.1.6 on 2025-03-23 03:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_vereador_cpf_alter_vereador_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamaraMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('papel_de_parede', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem de fundo')),
            ],
        ),
    ]
