# Generated by Django 5.1.6 on 2025-03-23 17:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_camaramunicipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaramunicipal',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo da Câmara'),
        ),
    ]
