# Generated by Django 5.1.6 on 2025-03-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronometro',
            name='tempo_extra',
            field=models.IntegerField(default=0),
        ),
    ]
