# Generated by Django 5.1.6 on 2025-03-27 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cronometro_tempo_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camaramunicipal',
            options={'verbose_name': 'Câmara Municipal', 'verbose_name_plural': 'Câmaras Municipais'},
        ),
        migrations.AlterModelOptions(
            name='cronometro',
            options={'verbose_name': 'Cronômetro', 'verbose_name_plural': 'Cronômetros'},
        ),
        migrations.AlterModelOptions(
            name='live',
            options={'verbose_name': 'Live', 'verbose_name_plural': 'Lives'},
        ),
        migrations.AlterModelOptions(
            name='pauta',
            options={'verbose_name': 'Pauta', 'verbose_name_plural': 'Pautas'},
        ),
        migrations.AlterModelOptions(
            name='presencaregistrada',
            options={'verbose_name': 'Presença Registrada', 'verbose_name_plural': 'Presenças Registradas'},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AlterModelOptions(
            name='sessao',
            options={'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
        migrations.AlterModelOptions(
            name='vereador',
            options={'verbose_name': 'Vereador', 'verbose_name_plural': 'Vereadores'},
        ),
        migrations.AlterModelOptions(
            name='votacao',
            options={'verbose_name': 'Votação', 'verbose_name_plural': 'Votações'},
        ),
        migrations.AddField(
            model_name='camaramunicipal',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camaramunicipal',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='O CNPJ deve estar no formato 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')]),
        ),
        migrations.AddField(
            model_name='camaramunicipal',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camaramunicipal',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='camaramunicipal',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pauta',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
